### PR TITLE
Double-width icons can cause duplicated first characters in the filename on macOS

### LINKED ISSUE #1692: O_NERD and O_EMOJI creates duplicate letters in filename
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS Ventura
- [x] Desktop Environment: Aqua
- [x] Terminal Emulator: kitty, Alacritty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: none
- [x] Configuration options set: O_NERD
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Clone the repo, enable nerdfonts in the `makefile`
```makefile
O_NERD := 1  # support icons-nerdfont
```
and compile with `LDLIBS="-L/opt/homebrew/opt/ncurses/lib/" make`.

Some files (with certain icons it appears) have duplicate initial letters as seen in the screenshot below:
Screenshot 2023-07-14 at 11 48 58

as soon as I select the makefile it will also have the duplicate initial letter:
Screenshot 2023-07-14 at 11 54 34

I have done some testing, this seems to also happen with `O_EMOJI` is set to enabled:
Screenshot 2023-07-14 at 11 56 51

 but not with `O_ICONS` enabled:
Screenshot 2023-07-14 at 11 57 37

I have peeked into the source code to find what is different between those options, but did not find a convincing clue.

I have also checked with kitty and alacritty, they both face the same problem.

These are the dynamic libs used by nnn:
```bash
 x otool -L ./nnn
./nnn:
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/opt/homebrew/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

### PR DESCRIPTION
**Pull request by quantonganh**
Fix #1692

### CODE REVIEW

**Comment by quantonganh** [comment]
Why this failed?

```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Cloning git repository
Enumerating objects: 17975, done.
Counting objects: 100% (164/164), done.
Compressing objects: 100% (80/80), done.
Total 17975 (delta 88), reused 135 (delta 81), pack-reused 17811

error fetching: couldn't find remote ref "refs/pull/1711/head"
```

**Comment by jarun** [comment]
Can you please make the change macOS-specific?

File: src/nnn.c [hunk 1]
```diff
@@ -6520,6 +6520,10 @@ static void draw_line(int ncols)
 	}
 
 	move(2 + last - curscroll, 0);
+#if defined(ICONS_ENABLED) && defined(__APPLE__)
+	clrtoeol();
+	refresh();
```
Comment (N-R-K) [inline src/nnn.c:6525]: Is the `refresh()` also needed? What happens without it?

Comment (quantonganh) [reply src/nnn.c:6525]: The issue still persists if we do not refresh the screen:

Screen Shot 2023-08-10 at 06 15 45

Comment (N-R-K) [reply src/nnn.c:6525]: I was thinking we can avoid unnecessary flushes. But the performance impact here doesn't seem too noticeable (unlike https://github.com/jarun/nnn/pull/1694). So we can probably merge this in as a hack until someone comes up with something better.

Could you please add a comment under the `#ifdef` referencing the original issue url? And also leave a comment stating that there might be a better way to fix it without a flush (so that it's easily visible to anyone else interested in this) @quantonganh

File: src/nnn.c [hunk 2]
```diff
@@ -6520,6 +6520,10 @@ static void draw_line(int ncols)
 	}
 
 	move(2 + last - curscroll, 0);
+#if defined(ICONS_ENABLED) && defined(__APPLE__)
```
Comment (N-R-K) [inline src/nnn.c:6523]: Instead of duplicating this, you can put this in a single place on top of the file:

```c
#if defined(ICONS_ENABLED) && defined(__APPLE__)
#define macos_icon_hack() do { clrtoeol(); refresh(); } while(0)
#else
#define macos_icon_hack()
#endif
```

Then just use `macos_icon_fix()` in those places.

Comment (quantonganh) [reply src/nnn.c]: I have made the updates as you suggested. Kindly review them.

**Review by N-R-K — APPROVED** [review]

File: src/nnn.c [hunk 3]
```diff
@@ -131,6 +131,18 @@
...
 #endif
 
+#if defined(ICONS_ENABLED) && defined(__APPLE__)
+/*
+ * For some reason, wcswidth returns 2 for certain icons on macOS
+ * leading to duplicated first characters in filenames when navigating.
+ * https://github.com/jarun/nnn/issues/1692
+ * There might be a better way to fix it without requiring a refresh.
+ */
+#define macos_icons_hack() do { clrtoeol(); refresh(); } while(0)
```
Comment (jarun) [inline src/nnn.c:141]: Why do we need a do while loop for this?

**Review by jarun — CHANGES_REQUESTED** [review]

File: src/nnn.c (hunk 3 above)
Comment (N-R-K) [reply src/nnn.c:141]: It's a common idiom to avoid surprises when used inside if statements. E.g

```c
if (c)
    MACRO();
```

Will not work without the `do {} while(0)` trick because it'll expand to this:

```c
if (c)
    statement_1;
statement_2;
```

Comment (jarun) [reply src/nnn.c:141]: Can't we just have the braces:

#define macos_icons_hack() { clrtoeol(); refresh(); }

Comment (N-R-K) [reply src/nnn.c:141]: Then you won't be able to put the semi-colon when invoking the macro. From [c-faq 10.4](https://c-faq.com/cpp/multistmt.html):

> If the macro expanded to a simple compound statement, the final, caller-supplied semicolon would be a syntax error:

```c
if (cond)
	{ stmt1; stmt2; };
else	/* some other code */
```

**Comment by jarun** [comment]
Thank you!
